name: CI

on:
  push:
  pull_request:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew jar
        
    - name: Upload jar
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: swift-dingtalk-bot.jar
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar

    - name: Test
      run: |
        export BUILD_SUCCESS=1
        export PR_NUMBER=${{ github.event.pull_request.number }}
        export PR_TITLE=${{ github.event.pull_request.title }}
        export PR_PR_AUTHOR=${{ github.event.pull_request.user.id }}
        export PR_COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/commits)
        export RELEASE_TAG=${{ github.event.release.tag_name }}
        export RELEASE_BODY=${{ github.event.release.body }}
        export DING_ACCESS_SECRET=${{ secrets.DING_ACCESS_SECRET }}
        export DING_ACCESS_TOKEN=${{ secrets.DING_ACCESS_TOKEN }}
        export OSS_API_KEY=${{ secrets.OSS_API_KEY }}
        export OSS_API_SEC=${{ secrets.OSS_API_SEC }}
        export COMMIT_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA)
        export BUILD_OUTPUT_FILES=${GITHUB_WORKSPACE}/build/libs/dingtalk-action-robot-1.0.jar
        java -jar build/libs/dingtalk-action-robot-1.0.jar
        
        
